"""Builds scenes.yaml / automations.yaml items and merges them safely.

No Home Assistant imports: unit tested in tests/test_generator.py.

Generated items get stable ids (same learned day + time -> same id), so the
scene and automation editors can modify them. On a relearn:

* items we generated and the user has NOT touched are replaced,
* items the user edited in the frontend are kept as-is (unless discarding edits),
* anything else in the files is never touched.
"""
from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from typing import Any

from .learner import format_offset, scene_abs

WEEKDAY_KEYS = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
WEEKDAY_NAMES = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]


def item_hash(item: Mapping[str, Any]) -> str:
    raw = json.dumps(item, sort_keys=True, default=str)
    return hashlib.sha1(raw.encode()).hexdigest()


def scene_id(prefix: str, entry: Mapping[str, Any]) -> str:
    return f"{prefix}_{entry['day_key'].replace('-', '')}_{scene_abs(entry)}"


def automation_id(prefix: str, entry: Mapping[str, Any]) -> str:
    return f"{scene_id(prefix, entry)}_auto"


def label(title: str, entry: Mapping[str, Any], weekday: int) -> str:
    return f"{title} {WEEKDAY_NAMES[weekday]} {entry['day_key']} {format_offset(entry['t'])[:5]}"


def build_scene(sid: str, name: str, states: Mapping[str, dict]) -> dict[str, Any]:
    return {
        "id": sid,
        "name": name,
        "icon": "mdi:home-clock",
        "entities": {
            entity_id: {"state": value["state"], **(value.get("attributes") or {})}
            for entity_id, value in sorted(states.items())
        },
    }


def build_automation(
    aid: str, sid: str, alias: str, entry: Mapping[str, Any], domain: str
) -> dict[str, Any]:
    time_of_day = format_offset(entry["t"])
    automation: dict[str, Any] = {
        "id": aid,
        "alias": alias,
        "description": (
            f"Generated by Presence Simulator from {entry['day_key']} at {time_of_day}. "
            "Enabled while the simulation switch is on. Edits made here are kept on relearn."
        ),
        "mode": "single",
        "triggers": [{"trigger": "time", "at": time_of_day}],
        "conditions": [],
        "actions": [],
    }
    if len(entry["weekdays"]) < 7:
        automation["conditions"].append(
            {"condition": "time", "weekday": [WEEKDAY_KEYS[w] for w in entry["weekdays"]]}
        )
    if entry.get("max_delay", 0) > 0:
        automation["actions"].append(
            {"delay": {"seconds": "{{ range(0, %d) | random }}" % (entry["max_delay"] + 1)}}
        )
    automation["actions"].append(
        {"action": f"{domain}.activate_scene", "data": {"scene_id": sid}}
    )
    return automation


def merge(
    existing: list[Any],
    previous: Mapping[str, str],
    new_items: list[dict[str, Any]],
    discard_edits: bool = False,
) -> tuple[list[Any], dict[str, str], set[str]]:
    """Merge generated items into a YAML list.

    previous: {id: hash} of what we wrote last time.
    Returns (merged list, {id: hash} to remember, ids kept because the user edited them).
    """
    new_by_id = {item["id"]: item for item in new_items}
    merged: list[Any] = []
    kept: set[str] = set()
    for item in existing:
        item_id = item.get("id") if isinstance(item, Mapping) else None
        if item_id is not None and item_id in previous:
            if item_hash(item) != previous[item_id] and not discard_edits:
                merged.append(item)
                kept.add(item_id)
            continue  # ours and untouched (or discarding): replaced below
        if item_id is not None and item_id in new_by_id:
            kept.add(item_id)  # user already owns an item with this id; never clobber
        merged.append(item)

    remember: dict[str, str] = {}
    for item_id, item in new_by_id.items():
        if item_id in kept:
            continue
        merged.append(item)
        remember[item_id] = item_hash(item)
    for item_id in kept:
        if item_id in previous:
            remember[item_id] = previous[item_id]  # still ours, but edited
    return merged, remember, kept


def remove(existing: list[Any], ids: set[str]) -> list[Any]:
    return [i for i in existing if not (isinstance(i, Mapping) and i.get("id") in ids)]
